name: 'CD Production'
run-name: 'Continuous Deployment to Production'
on:
  push:
    branches: ['production']

jobs:
    Continuous-Deployment: 
        runs-on: ubuntu-latest
        environment: production
        steps:
          - name: Logging into production server and building the application
            uses: appleboy/ssh-action@v1.0.3
            with:
                host: ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USER }}
                key: ${{ secrets.SSH_PVT_KEY }}
                port: ${{ secrets.SSH_PORT || 22 }}
                script_stop: true
                script: |
                    export NVM_DIR="$HOME/.nvm"
                    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
                    cd monorepo-deployment
                    git pull origin production
                    pnpm install
                    pnpm run build
                    pm2 restart web-app
                    pm2 restart http-server
                    pm2 restart ws-server
