name: 'CD Staging'
run-name: 'Continuous Deployment to Staging'
on:
  push:
    branches: ['main']

jobs:
    Continuous-Deployment: 
        runs-on: ubuntu-latest
        environment: staging
        steps:
          - name: Logging into staging server and building the application
            uses: appleboy/ssh-action@v1.0.3
            with:
                host: ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USER }}
                key: ${{ secrets.SSH_PVT_KEY }}
                port: ${{ secrets.SSH_PORT || 22 }}
                script_stop: true
                script: |
                    # deployment script
                    echo $SHELL
                    echo $PATH
                    cd /home/hit/monorepo-deployment
                    echo "current user: $(whoami)"
                    git pull origin main
                    /root/.nvm/versions/node/v24.19.0/bin/pnpm install
                    /root/.nvm/versions/node/v24.19.0/bin/pnpm run build
                    pm2 restart web-app
                    sudo nginx -s reload
                    pm2 restart http-server
                    pm2 restart ws-server