name: 'CD Staging'
run-name: 'Continuous Deployment to Staging'
on:
  push:
    branches: ['main']

jobs:
    Continuous-Deployment: 
        runs-on: ubuntu-latest
        environment: staging
        steps:
          - name: Logging into staging server and building the application
            uses: appleboy/ssh-action@v1.0.3
            with:
                host: ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USER }}
                key: ${{ secrets.SSH_PVT_KEY }}
                port: ${{ secrets.SSH_PORT || 22 }}

          - name: Change the login user
            run: su - {{ secrets.USER }}

          - name: Change directory to the application
            run: cd /home/{{ secrets.USER }}/monorepo-deployment

          - name: build the application
            run: |
                git pull origin main
                pnpm install
                pnpm run build  

         # restart the web, http and ws server
          - run: |
                pm2 restart web-app
                sudo /usr/sbin/nginx -s reload
                pm2 restart http-server
                pm2 restart ws-server
